name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: payoww/kernel_xiaomi_rosemary
          ref: R
          submodules: true

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison flex libssl-dev make libncurses5-dev ccache \
            git wget curl build-essential zip libelf-dev

      - name: Download Clang Toolchain
        run: |
          mkdir -p toolchains && cd toolchains
          wget https://github.com/ZyCromerZ/Clang/releases/download/17.0.2-Stable/Clang-17.0.2-Stable.tar.gz
          tar -xvzf Clang-17.0.2-Stable.tar.gz
          echo "CLANG_PATH=$(pwd)/Clang-17.0.2-Stable" >> $GITHUB_ENV

      - name: Compile Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export CROSS_COMPILE=aarch64-linux-gnu-
          export PATH=$CLANG_PATH/bin:$PATH

          make O=out rosemary_defconfig
          make -j$(nproc) O=out \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CLANG_TRIPLE=aarch64-linux-gnu-

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: rosemary-kernel-image
          path: out/arch/arm64/boot/Image
        
