name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kernel Source
        uses: actions/checkout@v4
        with:
          repository: payoww/kernel_xiaomi_rosemary
          ref: R
          submodules: true

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison flex libssl-dev make libncurses5-dev ccache \
            git wget curl build-essential zip libelf-dev

      - name: Download Clang 17.0.2
        run: |
          mkdir -p toolchains && cd toolchains
    wget https://software.frc971.org/Build-Dependencies/github.com/llvm/llvm-project/releases/download/llvmorg-17.0.2/clang+llvm-17.0.2-x86_64-linux-gnu-ubuntu-22.04.tar.xz
    tar -xvJf clang+llvm-17.0.2-x86_64-linux-gnu-ubuntu-22.04.tar.xz
    echo "CLANG_PATH=$(pwd)/clang+llvm-17.0.2-x86_64-linux-gnu-ubuntu-22.04" >> $GITHUB_ENV

      - name: Compile Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export CROSS_COMPILE=aarch64-linux-gnu-
          export PATH=$CLANG_PATH/bin:$PATH

          make O=out rosemary_defconfig
          make -j$(nproc) O=out \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CLANG_TRIPLE=aarch64-linux-gnu-

      - name: Upload Kernel Image
        uses: actions/upload-artifact@v4
        with:
          name: rosemary-kernel-image
          path: out/arch/arm64/boot/Image
        
